before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - apt-get install -qq curl
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  
   
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: lycee-gen-technologique.pro.dns-orange.fr
  script:
    - ssh btssio@lycee-gen-technologique.pro.dns-orange.fr "cd /var/www/html/mathisb/matete/matete-web && docker-compose down && git checkout deploiement-mathis && git pull origin deploiement-mathis && docker-compose build --no-cache --pull && docker-compose up -d && exit"
  only:
    - deploiement-mathis

Tests:
  image: php:8.0-apache
  stage: test
  script:
    - cd matete-web
    - composer update
    - php bin/phpunit
  allow_failure: false