Tests:
  image: php:8.0-apache
  stage: test
  services:
      - name: mysql:5.7
        alias: mysql
  variables:
      MYSQL_ROOT_PASSWORD: pass_test
      MYSQL_DATABASE: matetetest_test
      MYSQL_USER: matetetest
      MYSQL_PASSWORD: matetetest
      DATABASE_URL: 'mysql://matetetest:matetetest@mysql:3306/matetetest'
  before_script:
      - cd /matete-web
      - apt-get update && apt-get install -y git libzip-dev npm nodejs
      - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
      - docker-php-ext-install mysqli pdo pdo_mysql zip
      - composer install
      - npm install
      - php bin/console doctrine:database:drop --force --env=test
      - php bin/console doctrine:database:create --env=test
      - php bin/console doctrine:migration:migrate --no-interaction --env=test
      - php bin/console doctrine:fixtures:load --no-interaction --env=test
  script:
      - cd /matete-web
      - php bin/phpunit