before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - apt-get install -qq git wget
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - wget https://phar.phpunit.de/phpunit-9.3.7.phar
  - chmod +x phpunit-9.3.7.phar
  - mv phpunit-9.3.7.phar /usr/local/bin/phpunit  
  
   
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: lycee-gen-technologique.pro.dns-orange.fr
  script:
    - ssh btssio@lycee-gen-technologique.pro.dns-orange.fr "cd /var/www/html/mathisb/matete/matete-web && docker-compose down && git checkout master && git pull origin master && docker-compose build --no-cache --pull && docker-compose up -d && exit"
  only:
    - master

test:
  image: php:8.0-apache
  stage: Tests
  services:
    - name: mysql:5.7
  alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: pass_test
    MYSQL_DATABASE: mathismatete
    MYSQL_USER: user
    MYSQL_PASSWORD: AccessPlusC0mplique
    DATABASE_URL: 'mysql://user:AccessPlusC0mplique@mysql:3307/mathismatete'
    before_script:
      - apt-get update && apt-get install -y git libzip-dev npm nodejs
      - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
      - docker-php-ext-install mysqli pdo pdo_mysql zip
      - composer install
      - npm install
  script:
    - php bin/phpunit
  allow_failure: true