Tests:
  image: php:8.0-apache
  stage: test
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: AccessPlusC0mplique
    MYSQL_DATABASE: mateteRomain
    MYSQL_USER: user
    MYSQL_PASSWORD: AccessPlusC0mplique
    DATABASE_URL: 'mysql://user:AccessPlusC0mplique@mysql:3306/mateteRomain'
  before_script:
    - cd /var/www/html/matete/matete-web
    - apt-get update && apt-get install -y git libzip-dev npm nodejs
    - curl -sSk https://getcomposer.org/installer | php --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip
    - composer install
    - npm install
  script:
    - cd /var/www/html/matete/matete-web/
    - php bin/phpunit
  allow_failure: true