before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: lycee-gen-technologique.pro.dns-orange.fr
  script:
    - ssh btssio@lycee-gen-technologique.pro.dns-orange.fr "cd /var/www/html/mathisb/matete/matete-web && docker-compose down && git checkout deploiement-mathis && git pull origin deploiement-mathis && docker-compose build --no-cache --pull && docker-compose up -d && exit"
  only:
    - deploiement-mathis

Tests:
  image: php:8.0-apache
  stage: test
  script:
    - cd matete-web
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 
    - php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - composer update
    - php  bin/phpunit
  allow_failure: false