#ajout du SAST
image: jakzal/phpqa:latest
cache:
  paths:
    - vendor/
stages:
  - SecurityChecker
  - CodingStandards
  - test
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git wget
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  
SecurityChecker:
  stage: SecurityChecker
  script:
    - local-php-security-checker --path=./composer.lock
  allow_failure: false

phpcs:
 stage: CodingStandards
 script:
 - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
 allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false

test:
  image: php:8.0-apache
  stage: test
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: pass_test
    MYSQL_DATABASE: matetetest_test
    MYSQL_USER: matetetest
    MYSQL_PASSWORD: matetetest
    DATABASE_URL: 'mysql://matetetest:matetetest@mysql:3306/matetetest'
  before_script:
    - cd matete-web 
    - apt-get update && apt-get install -y git libzip-dev npm nodejs wget
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip 
    - composer install
    - npm install
    - php bin/console doctrine:database:drop --force --env=test
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:migration:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

  script:
    
    - php bin/phpunit
  allow_failure: false

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: lycee-gen-technologique.pro.dns-orange.fr
  script:
   - ssh btssio@lycee-gen-technologique.pro.dns-orange.fr "cd /var/www/html/tommy/matete/matete/matete-web && docker-compose down && git checkout DeploiementTommy && git pull origin DeploiementTommy && docker-compose build --no-cache --pull && docker-compose up -d && exit"
  only:
    - DeploiementTommy
